"""Added hashid column

Revision ID: 48fb27fa5a41
Revises: 20ec16d9c6e4
Create Date: 2026-04-19 23:49:29.872078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fb27fa5a41'
down_revision = '20ec16d9c6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashid', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('hashid')

    # ### end Alembic commands ###
